apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: my-app
    appstudio.openshift.io/component: devfile-sample-code-with-quarkus-zht0
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-zht0
  namespace: beaumorley-tenant
spec:
  url: https://github.com/beaumorley/devfile-sample-code-with-quarkus
